services:
  - type: web
    name: astro-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: export PYTHONPATH=$PYTHONPATH:. && gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
